module.exports = {
  ADD_MESSAGE: "ADD_MESSAGE",
  GET_MESSAGES: "GET_MESSAGES",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  LOGIN: "LOGIN",
  LOGIN_ERROR: "LOGIN_ERROR",
  VERIFY_LOGIN: "VERIFY_LOGIN",
};
